### ISSUE TITLE
Mozilla公式Polyfillは使ってる?

### ISSUE THREAD

**Issue by akku1139** [nakasyou/FireCws#14]
かなり優秀な模様
https://github.com/mozilla/webextension-polyfill

**Comment by akku1139** [comment]
> This library allows extensions that use the Promise-based WebExtension/BrowserExt API being standardized by the [W3 Browser Extensions](https://www.w3.org/community/browserext/) group to run on Google Chrome with minimal or no changes.

ChromeにFirefoxのadd-onをインスコするためのPolyfillだったみたい
これの逆を自力で実装する方法はあるけどそれは別のお話

**Comment by nakasyou** [comment]
@akku1139 
なるほど
> これの逆を自力で実装する方法はあるけどそれは別のお話

それをやるのがこのプロジェクトです
