### ISSUE TITLE
Releases の xpi 形式が誤っている

### ISSUE THREAD

**Issue by Ryosuke-Asano** [nakasyou/FireCws#4]
extensions フォルダー下に本体が存在しているため、Nightly や Dev Editon、Floorp では直接インストールできなくなっています。

以下のファイルを .xpi にリネームして再アップロードされることを推奨します。
[firefox.zip](https://github.com/nakasyou/FireCws/files/12620221/firefox.zip)

**Comment by nakasyou** [comment]
長い間気が付きませんでした。ごめんなさい。

ディレクトリ変更の際、ビルドスクリプトを正しく変更できていないのが問題でした。

[0.1.3](https://github.com/nakasyou/FireCws/releases/tag/0.1.3)から修正されますので、もし使用されるのであれば、そちらをお使いください。
